sudo: false
language: elixir
elixir: 1.2.1
addons:
  - postgresql: "9.4"
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
env:
  global:
    - MIX_ENV=test
